In [79]:
import numpy as np


In [80]:
# 배열 생성 방법 1
list1 = [1, 2, 3]
arr = np.array(list1)

print(list1)
print(arr)

[1, 2, 3]
[1 2 3]


In [81]:
# 배열 생성 방법 2
arr2 = np.array([[4, 5, 6],
                [1, 2, 3]])
print(arr2)

[[4 5 6]
 [1 2 3]]


In [82]:
print(type(list1))
print(type(arr))
print(type(arr2))
print(arr2.shape)
print(arr2.size)

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2, 3)
6


In [83]:
print((2,))
print(type((2,)))

(2,)
<class 'tuple'>


In [84]:
# 배열의 데이터 타입 확인하는 .dtype
print(arr2.dtype)
# 배열의 데이터 타입 변경하는 .astype()
arr3 = arr2.astype(float)
print(arr3)
print(arr3.dtype)

int32
[[4. 5. 6.]
 [1. 2. 3.]]
float64


In [85]:
arr1 = np.array(['a','b','c'], dtype='<U1')
print(arr1.dtype)

<U1


In [86]:
# 배열의 차원을 확인하는 속성 .ndim
print(arr2.ndim)

2


In [87]:
# array에 0으로 채워진 배열을 생성하는 방법
arr_zeros = np.zeros((2,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [88]:
# 1로 채워진 배열을 생성하는 방법
arr_ones = np.ones((2, 4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [89]:
# 특정 값으로 array를 빠르게 생성하는 방법
arr_full = np.full((3, 3), 7)
print(arr_full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [90]:
# 1~50까지 배열을 생성하는 방법
arr_range = np.arange(1, 51)
print(arr_range)
arr_range = np.arange(1, 51).reshape(5, 10) # 1~50까지 (5, 10)으로
print(arr_range)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [91]:
# 랜덤 수를 사용해 배열 생성!
print(np.random.rand(1, 5)) # (행, 열)
print(np.random.randint(1, 10)) # (~에서, ~까지)

[[0.7414626  0.61926983 0.58531945 0.08734695 0.60815281]]
8


### numpy의 인덱싱과 슬라이싱

In [92]:
arr1 = np.array(list1 + [4])
arr2 = np.array([list1 + [4], [5, 6, 7, 8]]) # 2차원 배열로 생성
print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [93]:
# 1차원 리스트에서 인덱싱, 슬라이싱
print(arr1[2:4])
# 2차원 배열에서 인덱싱, 슬라이싱
print(arr2[0][1:])
print(arr_range[2:4,1:4])#[[행1,행2],[열1,열2]]

[3 4]
[2 3 4]
[[22 23 24]
 [32 33 34]]


In [94]:
asd = np.array(['qwe','asd','zxc'])
print(type(asd))
print(asd.dtype)
asd

<class 'numpy.ndarray'>
<U3


array(['qwe', 'asd', 'zxc'], dtype='<U3')

In [95]:
print(arr_range[2:4,1:4])

# arr_arange[[행1,행2],[열1,열2]]
print(arr_range[[2,3],[3,3]])

[[22 23 24]
 [32 33 34]]
[24 34]


In [96]:
print(arr_range[1:4, 0:4:2])
arr_range[1:4,[0,2]]

[[11 13]
 [21 23]
 [31 33]]


array([[11, 13],
       [21, 23],
       [31, 33]])

In [97]:
print(arr_range[:, ::3])

[[ 1  4  7 10]
 [11 14 17 20]
 [21 24 27 30]
 [31 34 37 40]
 [41 44 47 50]]


### boolean 인덱싱 -> 색인

In [98]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1 >= 3

array([False, False,  True,  True,  True])

In [114]:
bol = np.array([True, False, False, True, False])
print(arr1[bol])

[1 4]


## Numpy 데이터 분석 BMI 지수 구하기

In [106]:
# 1. 사용하고자 하는 데이터 로드!
# np.loadtxt('데이터의 경로(폴더/파일이름.확장자)',데이터의 구분자)
data = np.loadtxt('data/height_weight.txt', delimiter=',')

numpy.ndarray

In [101]:
print("차원 : {}차원".format(data.ndim))
print("타입 : {}".format(data.dtype))
print("개수 : {}".format(data.size))
print("행, 열 : {}".format(data.shape))

차원 : 2차원
타입 : float64
개수 : 20
행, 열 : (2, 10)


In [105]:
height = data[0] / 100
weight = data[1]
print(height)
print(weight)

[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


In [104]:
bmi = (weight/(height**2))
print(bmi)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


In [120]:
# 과체중과 비만인 데이터 -> boolan 인덱싱 적용
bolen = bmi >= 23
bmi[bolen] # True
bmi[~bolen] # False

array([21.37153104, 16.03543423, 20.14486193, 21.69720651])

In [122]:
# 특정 범위 데이터 가져오기
bmi[(bmi>= 18.5) & (bmi < 23)]

array([21.37153104, 20.14486193, 21.69720651])